### ISSUE TITLE
[Feat] mid term task2 - seosonal_sales

### ISSUE THREAD

**Issue by KIM-DKA** [KIM-DKA/online_mall#24]
- [x] 2. 시즌별 매출 변화 및 수량 변화 분석
* 과제 2-1: 시즌별 매출 변화 및 구매 수량 트렌드 (seosonal_sales_trend) 
* 과제 2-2: 시즌별 가장 많이 팔린 품목 Top 20 (seosonal_top_sales)
* 과제 2-3: 시즌별 많이 팔린 비율 정리 (파이토, 항암, 유기농, 미네랄) (seosonal_keyword_top_sales)
* 과제 2-4: 시즌별 많이 구매한 회원 등급 (seosonal_member_type_sales)

**Comment by yeonjun-git** [comment]
resolve #24
schema: seasonal_sales
table:
- [x] seasonal_sales_base.sql 
- [x] seasonal_sales_trend.sql
- [x] seasonal_top_sales.sql
- [x] seasonal_keyword_top_sales.sql
- [x] seasonal_member_type_sales
