### ISSUE TITLE
[Feat] mid term task3 - member_type_top_salse

### ISSUE THREAD

**Issue by KIM-DKA** [KIM-DKA/online_mall#25]
- [x] 3. 회원 유형별 추세 분석 (월별, 요일별)
* 과제 3-1: 회원 유형별, 요일별 구매 제품 Top 20 (date_member_type_top_sales) 
* 과제 3-2: 회원 유형별, 월별 구매 제품 Top 20 (month_member_type_top_sales)

**Comment by yeonjun-git** [comment]
resolve #25
schema: member_type_top_sales
table:
- [x] date_member_type_top_sales.sql
- [x] month_member_type_top_sales.sql
