### ISSUE TITLE
[Feat] mid term task4 - new_member_top_salse

### ISSUE THREAD

**Issue by KIM-DKA** [KIM-DKA/online_mall#26]
- [x] 4. 신규 고객(실버, 골드) 많이 구매하는 제품 Top 20
* 과제 4: 신규 고객 구매 제품 Top 20 분석 (new_member_top_sales)

**Comment by yeonjun-git** [comment]
resolve #26
schema: member_type_top_sales
table:
- [x] new_member_top_sales.sql
